### ISSUE TITLE
Limited 3 domain for browser handling policy

### ISSUE THREAD

**Issue by minitomychannanathil** [WICG/first-party-sets#112]
Hello,
It seems that we are limited to upto 3 domains to share first-party set. But any more than that would result in auto-reject. This restriction would seem to work against publishers, who would have multiple websites/properties to consider.
How can this be handled?

**Comment by johannhof** [comment]
Hi @minitomychannanathil, please see  #93 and #96 where we're collecting feedback on these questions. It would be great to know what use cases you're looking at to determine whether they require a different API and/or subsets to ensure privacy and user understanding.

I'll close this issue, please follow up on e.g. #93.
