### ISSUE TITLE
Announcement: Privacy Sandbox Developer Office Hours #6: First-Party Sets

### ISSUE THREAD

**Issue by johannhof** [WICG/first-party-sets#121]
The Google Chrome team will be hosting our next external office hours sessions where we will provide some Privacy Sandbox tester updates and answer all your questions with product and technical leads. 

This time the topic will be First-Party Sets, so the session may be of interest to participants of this group.

The first North America/LATAM/EMEA friendly session is happening on Dec 15th 8-9am PST. A second Japanese language session is happening Dec 20th 6-7pm PST.  Both will use the same information below to join;

Video call link: https://meet.google.com/xnp-mxct-qvd
Or dial: ‪(US) +1 651-867-0444‬ PIN: ‪530 909 558‬#
More phone numbers: https://tel.meet/xnp-mxct-qvd?pin=9840654025397

A recording of the presentation portion will be shared after the events via our [Chrome Developer YT Channel](https://www.youtube.com/c/GoogleChromeDevelopers). 

We hope this is a helpful forum, and welcome your feedback and suggestions on how to make these events most useful for you as we experiment with different approaches.

**Comment by timcappalli** [comment]
@johannhof do you know when the recording will be posted?

**Comment by jwrosewell** [comment]
@johannhof can you advise if the recording is available yet?

**Comment by krgovind** [comment]
The recording can now be viewed [here](https://drive.google.com/file/d/1riGrGwP5cyz3q4IcDjV5kulOK48OJV2S/view), and is also linked off of the Privacy Sandbox events landing page [here](https://developer.chrome.com/docs/privacy-sandbox/events/#oh06).

**Comment by johannhof** [comment]
Thanks Kaustubha! Closing this issue for archival.
