### ISSUE TITLE
Broken link to directed identifiers in explainer

### ISSUE THREAD

**Issue by chrisn** [WICG/first-party-sets#131]
The [Applications](https://github.com/WICG/first-party-sets#applications) section in the explainer refers to WebID directed identifiers, but the link is broken. Should it be https://github.com/fedidcg/FedCM/blob/main/explorations/directed_identifiers.md? Also WebID should be FedCM?

**Comment by dmdabbs** [comment]
Also a couple of references remain to the deprecated CHIPS integration.

**Comment by krgovind** [comment]
Yes, sorry, those should be removed.
