### ISSUE TITLE
Feedback ElTiempo

### ISSUE THREAD

**Issue by AnalyticsElTiempo** [WICG/first-party-sets#146]
Company: El Tiempo Casa Editorial, a media conglomerate and owner of El Tiempo, the largest circulated daily newspaper in Colombia.

3P cookie usage across O&O domains: We share information between our 10+ domains through cookies for advertising campaigns through a DMP. Examples: www.ElTiempo.com, www.portafolio.co, www.futbolred.com, www.motor.com.co, www.elempleo.com, www.diarioadn.co, www.alo.co, www.caustica.co, www.CityTV.com.co, etc.

Future affected processes: Besides advertising-related use cases, we anticipate users having a less personalized experience when browsing through our domains. Before long, we want to be able to recommend content that users are likely to be interested in based on their browsing history (e.g. career related articles at eltiempo.com for users looking for jobs at elempreo.com).

First-Party Sets: We have reviewed the First-Party Sets policy and our only concern is that the Associated Subset is limited to 3 domains, which is too restrictive. We think that 10-15 domains would be a good balance between privacy and utility for users:

- It would allow publishers to personalize content for their users without compromising their privacy.
- It would still be a significant improvement over the current situation, where third-party cookies are used to track users across multiple websites.
- It would be a good compromise between the needs of publishers and the privacy concerns of users.

We’d like the 3-domain limit for the Associated Subset to be reconsidered by taking into account the impact that blocking third-party cookies will have on user experience and on publishers' ability to monetize their content.

**Comment by krgovind** [comment]
Thanks for the feedback, @AnalyticsElTiempo! We are collected feedback on the associated subset numeric limit in #93, so I've [captured your feedback there](https://github.com/WICG/first-party-sets/issues/93#issuecomment-1522460470).
