### ISSUE TITLE
Governance questions

### ISSUE THREAD

**Issue by jwrosewell** [WICG/first-party-sets#15]
The discussion in the [W3C Improving Web Advertising Business Group](https://www.w3.org/community/web-adv/) this week, specifically in relation to First Party sets, once again raises the issue of governance of the various proposals that have been put forth. Like Turtledove/Sparrow, the proposals around first party sets imply (in fact, they require) a governance structure. Specifically, the group discussed that in some cases independent domains should be allowed to federate browser data, while in other cases this would not be allowed. This means a decisioning structure needs to be put in place to provide basic rules for what federation(s) would be allowed, and to potentially adjudicate requests and violations.

This same requirement is central to the debate over Turtledove and Sparrow, where the main discussion is around what entities have access to end user content consumption data and are responsible for creating the cohorts and populating the reporting structures. 

In both cases, it seems implied that the only “governance” is the browsers themselves, and that this governance will be opaque (not necessarily published, without clearly visible procedures).

This proposal needs an explicit understanding of what governance structures are being proposed. There needs to be success criteria for the application of these policies. These criteria should benefit all stakeholders including browser vendors who would avoid any appearance of collusion that could otherwise be viewed as stifling competition. The W3C Improving Web Advertising Business Group have developed a draft of such [succes criteria](https://github.com/w3c/web-advertising/blob/master/success-criteria.md).

Recognizing there are important questions to address in finalizing these success criteria to evaluate first-party sets and other similar proposals aimed at improving web advertised. A non-exhaustive list below highlights some of these issues that deserve greater attention:

-	What safeguards are in place to ensure that browser decisions are not unilateral and are consistent with the agreed norms for content owners, marketers who fund them and other stakeholders?

-	If for-profit companies govern certain content consumption data collection and processing activities, and if so, what is the minimum number required for a competitive open market as well as should there be limits on the number of these governing authorities?

-	How should cross-publisher data sharing permissions be granted, administered and audited?

-	Which risks to people will these changes reduce or eliminate? 

-	Should people be given the right to overrule default settings to further restrict or more broadly allow the collection and processing of their content consumption data?

_Also posted on [TAG review](https://github.com/w3ctag/design-reviews/issues/342)_

_Also posted on [discourse]( https://discourse.wicg.io/t/proposal-first-party-sets/3331/7?u=jwrosewell)_.

**Comment by johannhof** [comment]
This is an old piece of feedback that applied to a previous iteration of the FPS proposal. With the understanding that not all your concerns and questions may be satisfied, I'll close this issue for the purpose of keeping issues on this repository relevant. Feel free to re-iterate concerns or questions as they apply to the current proposal.

**Comment by bradisbell** [comment]
@jwrosewell Put it very well, and his original comment is still relevant.

These first-party sets are directly taking control away from the users and putting it in the hands of Google and few others.  User agents should not need to depend on lists like this, and their centralized control.  At a minimum, some clarification of governance is in order.
