### ISSUE TITLE
Register first_party_sets.JSON with IANA 

### ISSUE THREAD

**Issue by brownwolf1355** [WICG/first-party-sets#150]
I recommend that first_party_sets.JSON be registered with IANA (https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml) consistent with RFC 8615. It is a relatively straightforward process.

**Comment by sjledoux** [comment]
Thank you for you suggestion @brownwolf1355 . The current well-known URI we use, `related_website_set.json`,  has now been [registered with IANA](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml#:~:text=related%2Dwebsite%2Dset.json).
