### ISSUE TITLE
How to test the serviceSites option from the first_party_sets.JSON file?

### ISSUE THREAD

**Issue by jczekaj3** [WICG/first-party-sets#163]
I am trying to test `serviceSites` option from the [first_party_sets.JSON](https://github.com/GoogleChrome/first-party-sets/blob/main/first_party_sets.JSON) file (Google Chrome version `114.0.5735.133`):

```sh
open -a 'Google Chrome' --args \
  --enable-features='FirstPartySets:FirstPartySetsClearSiteDataOnChangedSets/1,StorageAccessAPI,StorageAccessAPIForOriginExtension,PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI' \
  --use-first-party-set='{"primary": "https://«primary»", "associatedSites": ["https://«associated»"], "serviceSites": ["https://«service»"]}'
```

(“Block third-party cookies” is enabled. “Allow related sites to see your activity in the group” is also enabled.)

Unfortunately, requests from `https://«service»` can not set cookies via `Set-Cookie` header on `https://«primary»` and `https://«associated»`.

Does the `serviceSites` option work at all? Or am I doing something wrong?

**Comment by cfredric** [comment]
Hi @jczekaj3, thanks for testing the feature!

Can you tell us more about how your application is trying to set and read cookies? Reading/writing cookies on service sites within First-Party Sets should work just fine, as long as nothing else (e.g. other cookie attributes) prevents the cookies from being read/set.

Additionally, can you confirm that your application is using [`document.requestStorageAccess`](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess) before accessing cookies (in the event that third-party cookies are blocked)?

**Comment by jczekaj3** [comment]
Indeed with `document.requestStorageAccessFor` everything works! Thanks for your help!
