### ISSUE TITLE
Embedded iframe not passing third party cookie

### ISSUE THREAD

**Issue by keithbuel** [WICG/first-party-sets#164]
I’m trying to test a very simplistic use case using FPS, but can’t seem to get it working.

We have an IDP on one domain, and many associated applications on different domains that need to interact with that IDP to obtain the logged in user information.

Scenario:

1. User navigates to domain1.com and logs in.
2. domain1.com sets session cookie at domain1.com
3. User navigates to domain2.com
4. domain2.com uses embedded iframe to make a call to domain1.com to get profile information of the logged in user.

With third party cookies enabled, the browser sends the sessions cookies associated with domain1.com, domain1.com verifies the cookie and returns the associated profile information.

With third party cookies disabled, the cookies are blocked and domain1.com can not determine who the  user is.

From the documentation, I assume that this is a supported use case.  Is this correct?

I am running chrome using the following command:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-features="FirstPartySets:FirstPartySetsClearSiteDataOnChangedSets/1,StorageAccessAPI,StorageAccessAPIForOriginExtension,PageInfoCookiesSubpage,PrivacySandboxFirstPartySetsUI" \
--use-first-party-set="{\"primary\": \"https://domain1.com\", \"associatedSites\": [\"https://domain2.com\"]}" \
https://domain2.com
```

chrome version:
Version 114.0.5735.133 (Official Build) (arm64)

I also have enabled:
Allow related sites to see your activity in the group.

I assume that when this is rolled out, that this option will be checked by default in chrome?

**Comment by cfredric** [comment]
Hi @keithbuel, thanks for testing out this feature!

Thanks for the info about your use case. If I understand correctly, the subresource request issued by domain2.com when loading the `src` of the domain1.com iframe is what is expected to include the session cookie? If so, then I suspect your application needs to do one of two things first:
1. domain2.com needs to call [`document.requestStorageAccessFor('https://domain1.com')`](https://github.com/privacycg/requestStorageAccessFor) (and ensure that the promise resolves) before loading the domain1 iframe. This fetch must use CORS in credentialed mode, e.g. by using the [`crossorigin` HTML attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin) or `credentials: 'include'` parameter of the [`fetch` API](https://developer.mozilla.org/en-US/docs/Web/API/fetch).
2. The domain1.com iframe needs to call `document.requestStorageAccess()` (and ensure that the promise resolves) before trying to issue a web request with its unpartitioned cookies. (This is necessary for security reasons; see https://github.com/privacycg/storage-access/issues/113 for more info.)

Note that both of these options require a gesture from the user (e.g. a click or keypress), in order for the promise to resolve.

If your application is already doing one of those things, please let me know, and I'll do some more brainstorming.

>I assume that when this is rolled out, that this option will be checked by default in chrome?

Yes, we plan to enable this feature in Chrome by default.

**Comment by keithbuel** [comment]
@cfredric Thank you for your quick response.

My (incorrect) assumption was that creating the domain associations (primary and associated) would be a drop in fix for re-enabling broken integrations based on third party cookies.  I think this was based on earlier versions of the proposal.


Can you confirm that the same process of using `document.requestStorageAccessFor('https://domain1.com')` would be required for ajax calls using `withCredentials: true` made to domain1.com from the domain2.com page?

**Comment by cfredric** [comment]
> Can you confirm that the same process of using `document.requestStorageAccessFor('https://domain1.com')` would be required for ajax calls using `withCredentials: true` made to domain1.com from the domain2.com page?

That's correct. If access to cross-site cookies is blocked by default (e.g. by enabling block-third-party-cookies), then using XHR with `withCredentials = true` will still not have access to those cookies unless `document.requestStorageAccessFor` or `document.requestStorageAccess` has been called beforehand.

And conversely, even if your application has called `document.requestStorageAccessFor` appropriately, XHRs sent by the top-level context (domain2.com, if I understand correctly) will not have access to cross-site cookies unless the XHRs use `withCredentials = true`, due to the CORS requirement. (XHRs sent by the embedded context [domain1.com] don't necessarily need `withCredentials = true`, since the CORS requirement only applies to `requestStorageAccessFor`, not `requestStorageAccess`.)

**Comment by keithbuel** [comment]
@cfredric thank you for the clarification.  I can close this issue as it appears that the flows are working as expected.
