### ISSUE TITLE
I think in this issue we've established some use cases for entities operating separate domains, which helped inspire the subset-based approach to FPS, e.g. the "service" domains that enable separation of content for security reasons, among other things. In our new proposal we've also acknowledged some of the concerns around common ownership as the primary criterion for set membership that were brought up here and in other places, and rely primarily on technical checks and assertions instead.

### ISSUE THREAD

**Issue by viviennhs1985202** [WICG/first-party-sets#174]
I think in this issue we've established some use cases for entities operating separate domains, which helped inspire the subset-based approach to FPS, e.g. the "service" domains that enable separation of content for security reasons, among other things. In our new proposal we've also acknowledged some of the concerns around common ownership as the primary criterion for set membership that were brought up here and in other places, and rely primarily on technical checks and assertions instead.

It seems appropriate to close this now.

_Originally posted by @johannhof in https://github.com/WICG/first-party-sets/issues/19#issuecomment-1401722462_

**Comment by nihasn773-cmyk** [comment]
[](url)
