### ISSUE TITLE
Help deciding if a proposal is the right next step

### ISSUE THREAD

**Issue by jdbohrman** [WICG/first-party-sets#186]
Hey everyone! My name is James and I'm a partner success manager who recently wrote this blog post about privacy and the depreciation of cookies. In it I give a detailed history of privacy, where we started, where we've been, and where we might be going. Near the end I highlighted a potential proposal for "ecosystem cookies" that are somewhat tied to Related Website Sets, and I wanted to know if this would be something that would be open to discussion or a proposal. Mainly I didn't want to tease it in the post and then not take any action. 

https://www.tryuppercut.com/partner-ecosystems-web-standards

> For a concept like second-party cookies to work as a solution, we need to rethink how we frame privacy, trust, and concept. Going back to my earlier analogy about who you would trust to follow you around the store, I believe that the majority of users would be more than happy to allow their ecosystem to track their activity if they had their trust. But without that important component, it’s an uphill battle to let anyone follow you around a store.
> 
> We’ve come up with an interesting proposal for ecosystem cookies, that implements a new standard similar to the [WICG’s Related Website Sets](https://github.com/WICG/first-party-sets), but for the purpose of consensual tracking of users in an ecosystem. Our proposal aims to bring trust back into the marketing world, while giving users the choice to trust their ecosystem with their information should the ecosystem have gained it.
> 
> Our planned proposal will allow partnered domains to act as their own central authority for connected domains, and define boundaries for data sharing across multiple domains. This will allow minimal “ecosystem cookies” to be shared cross-domain, with set boundaries declared. So for example, say you are the partner manager at hooli.com. With our proposed implementation of Ecosytem Sets, you could add a relation to piedpiper.com. Then, after provide a each other a verification key and implementing the relationships, you would now be able to support cross domain cookies from hoolie.com and piedpiper.com

**Comment by krgovind** [comment]
Hi @jdbohrman, thanks for the question.

As per my understanding, your proposal for "ecosystem cookies" is intended for ads/marketing use-cases. From the Chrome perspective, we are developing purpose-built APIs for ads relevance and measurement use-cases, which are our preferred set of solutions for these use-cases. Please see the list of APIs on [this landing page](https://privacysandbox.com/open-web/#proposals-for-the-web) - each proposal will link you to a blogpost that in turn links to GitHub repositories for that API, which you can ask questions on if you have feedback regarding the API or how it applies to use cases. I hope that helps!
