### ISSUE TITLE
Links in README are broken

### ISSUE THREAD

**Issue by estein-de** [WICG/first-party-sets#192]
https://github.com/WICG/first-party-sets#chromes-submission-guidelines-and-rws-canonical-list

These links are broken:

* "Submission Guidelines" which currently links to https://github.com/GoogleChrome/first-party-sets/blob/main/FPS-Submission_Guidelines.md is a 404 error. I don't know where the correct URL for this is.
* "canonical list" which currently links to https://github.com/GoogleChrome/first-party-sets/blob/main/first_party_sets.JSON I believe should be updated to point to https://github.com/GoogleChrome/related-website-sets/blob/main/related_website_sets.JSON

**Comment by cfredric** [comment]
Thank you! I've fixed those links.
