### ISSUE TITLE
Interacting with IFrame content as top-level document 

### ISSUE THREAD

**Issue by mahaboobalimahammad** [WICG/first-party-sets#197]
Hi,
In the documentation section 
https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration#checking_and_requesting_storage_access

It is mentioned that, it is mandatory for the users to interact with the IFrame url atleast once in the last 30 days as top-level document.

I have a chrome extension which creates an IFrame and embeds it with a popup.html page bundled with the extension package itself.

in this usecase, what url should the user visits to pass the above check ? 

I tried opening chrome-extension://my_id/popup.html in omnibox but it didn't solved my issue. Please suggest

**Comment by cfredric** [comment]
Hi @mahaboobalimahammad,

I think you're conflating the Storage Access API and Related Website Sets. Chrome's implementation of the Storage Access API requires the top-level user interaction *only if* the pair of sites are **not** in the same RWS; please see https://github.com/cfredric/chrome-storage-access-api#chrome-specific-behavior. So Chrome's top-level user interaction requirement is not relevant to this repository.

It's not possible to declare a Chrome extension as being part of a Related Website Set, but I believe that capability is unnecessary. If you want to access a site's cookies from a Chrome extension, consider using the `chrome.cookies` API and requesting "host_permissions" in your extension manifest. Please see https://developer.chrome.com/docs/extensions/reference/api/cookies.
