### ISSUE TITLE
Cloudflare JS Challenge cookie

### ISSUE THREAD

**Issue by BowFarmer** [WICG/first-party-sets#202]
In what category does the cookie Cloudflare puts on a website belong to? Many websites use Cloudflare's JS Challenge to protect pages such as login and checkout pages. Cloudflare does create a cookie from https://challenges.cloudflare.com during this process. How do sites specify that this cookie is allowed?

**Comment by krgovind** [comment]
From Cloudflare's product page, it's hard for me to tell if they store/use information collected across multiple customer sites. If information is maintained on a per-top-level-site basis,  adding the [Partitioned attribute](https://developers.google.com/privacy-sandbox/3pcd/chips) to the cookie would be the right option. If cross-site information is needed, [Private State Tokens](https://developers.google.com/privacy-sandbox/protections/private-state-tokens/developer-guide) may be a good replacement. Either way, Cloudflare would be responsible for the change, so I would recommend reaching out to them.
