### ISSUE TITLE
Is user gesture mandatory for related website sets to access third party cookie even the sites are in RWS.

### ISSUE THREAD

**Issue by sreek10** [WICG/first-party-sets#206]
I tried the related website sets demo from the link -> https://developers.google.com/privacy-sandbox/3pcd/related-website-sets-integration and I could see the potential ask of a user gesture to get the access for storage from primary website.
After the user gesture which is the button click, I am able to get the cookies from primary domain/website.

But the below link says otherwise where we don't need user gesture and access can be granted if the website falls under the set.

Can you please confirm the actual behavior.

Please find the screenshot - :

![RWS-Screenshot](https://github.com/WICG/first-party-sets/assets/158512841/95a89d77-59e3-4684-91be-6844dfa2ce39)

Please find the link to support above statement : -

https://developers.google.com/privacy-sandbox/3pcd/storage-access-api

**Comment by cfredric** [comment]
Hi @sreek10,

I addressed this in https://github.com/GoogleChrome/related-website-sets/issues/244#issuecomment-1922361492. Chrome does not require a user prompt for Storage Access requests within a Related Website Set, but Chrome does still require a user gesture even in this situation.

A user gesture and a user prompt are different things.
