### ISSUE TITLE
Critical feature request: partitioned cookies (CHIPS) and partitioned storage (Storage Partitioning) that can leverage Related Website Sets

### ISSUE THREAD

**Issue by kelvingraddick** [WICG/first-party-sets#212]
### **Background / Context**

I work for [LivePerson](https://www.liveperson.com/), a major web chat provider for companies like Microsoft, Verizon, The Home Depot, GoDaddy, and many more. 

Our web chat product is "embedded" – running as an application directly on the webpages of our customers listed above (_not in an iframe_), where typically we can use first party cookies / storage to store things like a user's chat identity, in order to maintain a conversation page-to-page.

![top-level-site-retailexa-b1bf622bc028e](https://github.com/WICG/first-party-sets/assets/3710765/edd70026-7a77-4d22-958d-548425152657)

However, some of our customers have multiple top-level domains (_ex. verizon.com and verizon-sales.com_) where they still need a consumer's chat identity / conversation maintained across. 
- Currently, our solution for that is based on using an iframe to set 3rd party cookies (_or other storage type_) against our own LivePerson domain, that can then be accessed across any of the brands different domains to maintain a user's identity/conversation – it worked for a long time..
- ..but of course now with the [3rd-party cookie deprecation](https://developers.google.com/privacy-sandbox/3pcd), and [Storage Partitioning](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning), this will not work anymore.

To be clear this is NOT an advertising tracking scenario, but simply a 3rd-party chat application scenario, that major brands are currently using.

### **Feature Request**
 
What we propose is that partitioned cookies ([CHIPS](https://developers.google.com/privacy-sandbox/3pcd/chips)) and/or partitioned storage ([Storage Partitioning](https://developers.google.com/privacy-sandbox/3pcd/storage-partitioning)) are automatically allowed to be accessed across the Related Website Set, without the need for the Storage Access API, nor user interaction. 

In other words, the cookies or storage is able to be partitioned/accessed per Related Website Set (if one is defined), and NOT just per single domain. For our scenario, this will allow a brand to define their related website set, and us to be able to still access partitioned cookies/storage across them, in order to maintain a user's chat identity and conversation across the related website set.

_**Why can't we just use the Storage Access API with Related Website Sets?**_
- Because Storage Access API requires user interaction with our iframe, and our application runs passively as code on our customers website.
- The iframe is only for 3rd-party storage and is hidden. 
- We need to know if this user has a current conversation to know whether to show the conversation or an invitation, without the user clicking.
- When a user is chatting and switches to another website page, they do not expect to have to click something for the same chat to resume. 
- It was stated that this scenario is not one Storage Access API was made for in the documentation [here](https://developers.google.com/privacy-sandbox/3pcd/storage-access-api#when_to_use_the_storage_access_api_over_other_apis).

<br />
Please let me know if you have any questions, feedback, and/or concerns. Thanks!

**Comment by krgovind** [comment]
Closing this as a duplicate since this was also [posted]( https://github.com/WICG/first-party-sets/issues/94#issuecomment-1998064308) on issue #94, where this is being discussed.
