### ISSUE TITLE
First-Party Sets naming

### ISSUE THREAD

**Issue by mlerra** [WICG/first-party-sets#27]
During the PrivacyCG face-to-face, the "First-Party Sets" name was brought up as a potential point of user confusion. 

A suggestion of "Privacy Sets" was offered.

Are there any other ideas for names that could be better understood by users than "First-Party Sets"?

**Comment by dmarti** [comment]
This is a good point. Going by "party" is not really applicable to a lot of real world use cases. (When a user reads the ToS they might find that if they're on one side of the Atlantic they have an agreement with example.com Inc. in the USA, and on the other side they have an agreement with example.com Limited in Ireland.)

To avoid the word "party" how about "Common Branding and Terms Sets"? Makes it clear that the user sees that they're interacting with the same company or cooperating group of companies sharing branding, and that the same policy (ToS and privacy policy) applies.

**Comment by mlerra** [comment]
Thank you for raising that point. I also think "party" and particularly the "first-party" term, may not be intuitively understood to users. 

Some ideas we could mix and match:
[Site/Entity/Organization/Affiliated/Data] 
[Groups/Walls/Limits/Spheres/Sets/Associations/Collections/Boundaries/Domains]

So for example:
- Affiliated Domains
- Data Boundaries
- Site Collections
- Site Limits 
etc.

Curious if anyone else has term suggestions to throw in, and/or a favorite combination of the above?

**Comment by michael-oneill** [comment]
The UA Policy Proposal introduces the idea of  one or more Independent Enforecement Entities, which might require and check manifest files that include domain ownership and other details. Why not merge the FP JSON resource with this so it becomes a set of objects in a common privacy.json manifest, at a .well-known location e.g. /.well-known/privacy.json

**Comment by johannhof** [comment]
Not sure if the name is perfect but this issue seems to have stalled so I'll close it for now. I don't think we're actively considering a name change right now, but we can revisit this if needed.
