### ISSUE TITLE
Enforcement against formation of large sets 

### ISSUE THREAD

**Issue by krgovind** [WICG/first-party-sets#29]
To aid user understanding, and prevent abuse, it is desirable to prevent the formation of excessively large sets. What are some ways to prevent or disincentivize formation of large sets?

- Technical limit on the size of a set: Is there a reasonable limit we can place on the number of domains in a set? 
   - ccTLD variants can number in the 100s. Should those be discounted against the limit?
- Storage limits: Could we apply counterpressure against formation of large sets by applying storage limits per set, instead of per domain?
- Entropy limits: ~Could we apply counterpressure against formation of large sets by applying~ entropy limits (e.g. [Privacy Budget](https://github.com/bslassey/privacy-budget) ) will be applied per set, instead of per domain. Can these be an effective counterpressure?
- Other ideas?

**Comment by bslassey** [comment]
Since there will be communication within a set, Privacy Budget limits will have to apply to the entire set. Whether or not that is effective counterpressure to forming large sets can reasonably debated of course.

**Comment by krgovind** [comment]
> Since there will be communication within a set, Privacy Budget limits will have to apply to the entire set. Whether or not that is effective counterpressure to forming large sets can reasonably debated of course.

Indeed. Edited the original post to reflect this.

**Comment by hpsin** [comment]
@krgovind the size of the allowed set is of significant interest to established corporations like Microsoft, who have ~300 domains in use for our applications that we'd need to put in a single set. Is there a plan to place a hard upper limit on the set size? Happy to open this as a separate issue.

**Comment by othermaciej** [comment]
Hundreds of domains in a set has clear abuse potential. There should be some sort of limit.

**Comment by hpsin** [comment]
Agreed - there will always be tension with forcing changes and improving privacy.  We can pick winners amongst our apps if need be.  Understanding if the limit is 3 (non-starter for us, 3 barely covers our login pages) or 20, or 50, is a good starting point that we can use to drive domain convergence.

**Comment by krgovind** [comment]
@hpsin: Could you elaborate on whether all ~300 domains would need to be in the same set? 

- Do they all need access to the same user identity within a given browsing session? 
- Do some of them serve as utility domains that could make use of partitioned state? For instance, [Firefox is doing this](https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) in ETP strict mode.

  
Note that a single organization would have the ability to form multiple sets. For instance you could divide up your domains based on how users interact across them.

**Comment by johannhof** [comment]
I think this was solved through the subsets design and particularly limiting the number of "associated" subset members. There's still an open question whether the new design is able to solve all use cases properly (#96) but for now I'd say that in general the design is effective in preventing (non-contextual) large set formation.
