### ISSUE TITLE
User impact of first party sets

### ISSUE THREAD

**Issue by LALeVasseur** [WICG/first-party-sets#30]
Hi folks, 

A few considerations from the individual's and a legal point of view--forgive me if these have been addressed elsewhere (and please feel free to point me to the relevant issues). 

1. People experience a kind of "Me2P" relationship with a single service/app at a time. https://youtu.be/A7K4zX2H2yI They don't necessarily understand that they're having a relationship with multiple entities simultaneously [which of course, they already are, unknowingly].  First Party Sets seems likely to confuse people by adding even more services into the relationship.

2. People don't know the full product portfolio for organizations.  e.g. many people don't know that facebook owns Whatsapp.  

2.  From a legal perspective, the privacy policies and terms of service/use are specific to a single first party domain.  So this change necessitates a vendor to orchestrate/aggregate privacy policies and terms (at a minimum).

**Comment by johannhof** [comment]
I'll close this issue as part of a general cleanup. I think we recognized parts of this feedback (which has also been given by others) and tried to address it to the extent possible through the subsets design, providing stronger restrictions and technical verification for set members. It's important to note here that the goal of FPS is to enhance the user experience when interacting with a single entity which operates complex services that cross the site barrier for e.g. security or localization reasons, not to add(?) additional entities (and I hope the new design of the proposal makes that more clear).

We recognize that different user agents may have varying sensitivity in this question and are thus integrating with the SAA for cross-browser compatibility.
